
export default {
    SV_ALL_VALUES: 'SV_ALL_VALUES',
    SV_SENSOR_UPDATED: 'SV_SENSOR_UPDATED',
    SV_SENSOR_DATA: 'SV_SENSOR_DATA',

    SV_CONTROL_UPDATED: 'SV_CONTROL_UPDATED',
    SV_CONTROL_DATA: 'SV_CONTROL_DATA',

    SV_ALARM_STATE_UPDATED: 'SV_ALARM_STATE_UPDATED',
    SV_ALARM_STATE_DATA: 'SV_ALARM_STATE_DATA',

    SV_NEW_FRAME_ARRIVED: 'SV_NEW_FRAME_ARRIVED',
    SV_NEW_FRAME: 'SV_NEW_FRAME'
};
